version: "3.3"

networks:
  appnetwork:
    driver: bridge

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: statesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cxmdb.24#
    ports:
      - "5432:5432"
    networks:
      - appnetwork
    volumes:
      - database-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3003:3003"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:cxmdb.24#@database:5432/statesdb
    networks:
      - appnetwork

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  database-data:
